using System.Globalization;
using System.Text;
using System.Text.Json.Nodes;
using Microsoft.OpenApi;

namespace OpenApiCodeGenerator;

/// <summary>
/// Emits C# source code from OpenAPI schemas. Produces records, enums,
/// and type aliases in a modern C# style with nullable reference types.
/// </summary>
internal class CSharpCodeEmitter
{
    private readonly GeneratorOptions _options;
    private readonly TypeResolver _typeResolver;
    private readonly Dictionary<string, IOpenApiSchema> _allSchemas;
    private readonly HashSet<IOpenApiSchema> _knownSchemas;
    private readonly StringBuilder _sb = new();
    private int _indent;

    /// <summary>
    /// Maps a union variant schema → (resolved base type name, discriminator property name).
    /// Populated during <see cref="DiscoverInlineObjects"/> so that <see cref="EmitRecord"/>
    /// can emit the correct base type for variants of discriminated unions and skip the
    /// discriminator property (handled by the polymorphic serializer).
    /// </summary>
    private readonly Dictionary<IOpenApiSchema, (string BaseTypeName, string DiscriminatorPropertyName)> _unionVariantBaseTypes = new(ReferenceEqualityComparer.Instance);

    /// <summary>
    /// Maps (schemaName, propertyName) → resolved enum type name for inline enums.
    /// Built during <see cref="Emit"/> so that <see cref="EmitProperty"/> can reference
    /// the correct (possibly deduplicated or differentiated) enum type name.
    /// </summary>
    private Dictionary<(string SchemaName, string PropertyName), string> _inlineEnumMap = new();

    public CSharpCodeEmitter(
        GeneratorOptions options,
        TypeResolver typeResolver,
        IDictionary<string, IOpenApiSchema> allSchemas)
    {
        _options = options;
        _typeResolver = typeResolver;
        _allSchemas = new Dictionary<string, IOpenApiSchema>(allSchemas, StringComparer.Ordinal);
        _knownSchemas = new HashSet<IOpenApiSchema>(_allSchemas.Values, ReferenceEqualityComparer.Instance);
    }

    /// <summary>
    /// Emit the full C# source file for all schemas.
    /// </summary>
    public string Emit()
    {
        _sb.Clear();
        _indent = 0;

        // Two-pass type name resolution: detect collisions, assign clean names to
        // the most natural schema name, differentiate others meaningfully.
        Dictionary<string, string> typeNameMap = ResolveTypeNameCollisions(_allSchemas.Keys);

        // Hoist inline object schemas into synthesized named types so that
        // inline objects (properties defined as type:object with properties
        // directly, rather than via $ref) become proper C# records instead
        // of degrading to "object".
        // This must run before the converter checks below, so that hoisted
        // schemas (which may contain binary-stream properties) are visible
        // to ShouldEmit*JsonConverter and the converter classes get emitted.
        ResolveInlineObjects(typeNameMap);

        bool emitGenericTypeAliasConverters = ShouldEmitGenericTypeAliasConverters();
        bool emitBinaryStreamTypeAliasConverters = ShouldEmitBinaryStreamTypeAliasConverters();
        bool emitBinaryStreamJsonConverter = ShouldEmitBinaryStreamJsonConverter() || emitBinaryStreamTypeAliasConverters;
        bool emitValidationAttributes = ShouldEmitValidationAttributes();

        if (_options.GenerateFileHeader)
        {
            AppendLine("// <auto-generated>");
            AppendLine("// This file was auto-generated by OpenApiCodeGenerator.");
            AppendLine("// Do not make direct changes to the file.");
            AppendLine("// </auto-generated>");
            AppendLine();
        }

        AppendLine("#nullable enable");
        AppendLine("#pragma warning disable CS8019, CS9042");
        AppendLine();

        AppendLine("using System;");
        AppendLine("using System.Collections.Generic;");
        AppendLine("using System.Globalization;");

        if (emitBinaryStreamJsonConverter || emitBinaryStreamTypeAliasConverters)
        {
            AppendLine("using System.IO;");
        }

        if (emitGenericTypeAliasConverters || emitBinaryStreamJsonConverter || emitBinaryStreamTypeAliasConverters)
        {
            AppendLine("using System.Text.Json;");
        }

        AppendLine("using System.Text.Json.Serialization;");

        if (emitValidationAttributes)
        {
            AppendLine("using System.ComponentModel.DataAnnotations;");
        }

        AppendLine();

        AppendLine($"namespace {_options.Namespace};");
        AppendLine();

        if (emitGenericTypeAliasConverters || emitBinaryStreamTypeAliasConverters)
        {
            EmitTypeAliasInterface();
        }

        if (emitBinaryStreamJsonConverter)
        {
            EmitBinaryStreamJsonConverter();
        }

        if (emitGenericTypeAliasConverters)
        {
            EmitGenericTypeAliasJsonConverter();
        }

        if (emitBinaryStreamTypeAliasConverters)
        {
            EmitBinaryStreamTypeAliasJsonConverter();
        }

        // Pre-collect, deduplicate, and emit all inline enums before emitting records.
        // This ensures matching inline enums across schemas are emitted once, and
        // conflicting ones get differentiated names.
        _inlineEnumMap = ResolveInlineEnums(typeNameMap);
        EmitResolvedInlineEnums(_inlineEnumMap);

        foreach ((string? name, IOpenApiSchema? schema) in _allSchemas)
        {
            EmitSchemaWithTypeName(name, schema, typeNameMap[name]);
        }

        return _sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private bool ShouldEmitGenericTypeAliasConverters()
    {
        return !_options.InlinePrimitiveTypeAliases && _allSchemas.Values.Any(_typeResolver.UsesGenericTypeAliasJsonConverter);
    }

    private bool ShouldEmitBinaryStreamJsonConverter()
    {
        return _allSchemas.Values.Any(schema => CollectProperties(schema).Values.Any(propertySchema => _typeResolver.IsBinaryStreamPropertyType(propertySchema)));
    }

    private bool ShouldEmitBinaryStreamTypeAliasConverters()
    {
        return !_options.InlinePrimitiveTypeAliases && _allSchemas.Values.Any(schema => TypeResolver.IsTypeAlias(schema) && _typeResolver.IsBinaryStreamPropertyType(schema));
    }

    private bool ShouldEmitValidationAttributes()
    {
        if (!_options.EmitValidationAttributes)
        {
            return false;
        }

        return _allSchemas.Values.Any(schema => CollectProperties(schema).Values.Any(HasValidationConstraints));
    }

    private static bool HasValidationConstraints(IOpenApiSchema schema)
    {
        return schema.MinLength.HasValue ||
               schema.MaxLength.HasValue ||
               !string.IsNullOrEmpty(schema.Pattern) ||
               !string.IsNullOrEmpty(schema.Minimum) ||
               !string.IsNullOrEmpty(schema.Maximum) ||
               schema.MinItems.HasValue ||
               schema.MaxItems.HasValue;
    }

    private void EmitTypeAliasInterface()
    {
        AppendBlock("file interface IOpenApiGeneratedTypeAlias<TSelf, TValue>\n    where TSelf : struct, IOpenApiGeneratedTypeAlias<TSelf, TValue>", () =>
        {
            AppendLine("static abstract TSelf Create(TValue value);");
            AppendLine();
            AppendLine("TValue Value { get; }");
        });
        AppendLine();
    }

    private void EmitBinaryStreamJsonConverter()
    {
        AppendBlock("file sealed class OpenApiGeneratedBinaryStreamJsonConverter : JsonConverter<Stream>", () =>
        {
            AppendBlock("public override Stream? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)", () =>
            {
                AppendBlock("if (reader.TokenType == JsonTokenType.Null)", () =>
                {
                    AppendLine("return null;");
                });
                AppendLine();
                AppendBlock("if (reader.TokenType != JsonTokenType.String)", () =>
                {
                    AppendLine("throw new JsonException(\"Expected a base64-encoded string for binary content.\");");
                });
                AppendLine();
                AppendLine("string? base64 = reader.GetString();");
                AppendBlock("if (string.IsNullOrEmpty(base64))", () =>
                {
                    AppendLine("return new MemoryStream();");
                });
                AppendLine();
                AppendBlock("try", () =>
                {
                    AppendLine("byte[] bytes = Convert.FromBase64String(base64);");
                    AppendLine("return new MemoryStream(bytes, writable: false);");
                });
                AppendBlock("catch (FormatException exception)", () =>
                {
                    AppendLine("throw new JsonException(\"Expected a base64-encoded string for binary content.\", exception);");
                });
            });
            AppendLine();
            AppendBlock("public override void Write(Utf8JsonWriter writer, Stream? value, JsonSerializerOptions options)", () =>
            {
                AppendBlock("if (value is null)", () =>
                {
                    AppendLine("writer.WriteNullValue();");
                    AppendLine("return;");
                });
                AppendLine();
                AppendLine("long originalPosition = 0;");
                AppendBlock("if (value.CanSeek)", () =>
                {
                    AppendLine("originalPosition = value.Position;");
                    AppendLine("value.Position = 0;");
                });
                AppendLine();
                AppendBlock("try", () =>
                {
                    AppendLine("using var buffer = new MemoryStream();");
                    AppendLine("value.CopyTo(buffer);");
                    AppendLine("writer.WriteStringValue(Convert.ToBase64String(buffer.ToArray()));");
                });
                AppendBlock("finally", () =>
                {
                    AppendBlock("if (value.CanSeek)", () =>
                    {
                        AppendLine("value.Position = originalPosition;");
                    });
                });
            });
        });
        AppendLine();
    }

    private void EmitGenericTypeAliasJsonConverter()
    {
        AppendBlock("file sealed class OpenApiGeneratedTypeAliasJsonConverter<TAlias, TValue> : JsonConverter<TAlias>\n    where TAlias : struct, IOpenApiGeneratedTypeAlias<TAlias, TValue>", () =>
        {
            AppendBlock("public override TAlias Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)", () =>
            {
                AppendLine("TValue value = JsonSerializer.Deserialize<TValue>(ref reader, options)!;");
                AppendLine("return TAlias.Create(value);");
            });
            AppendLine();
            AppendBlock("public override void Write(Utf8JsonWriter writer, TAlias value, JsonSerializerOptions options)", () =>
            {
                AppendLine("JsonSerializer.Serialize(writer, value.Value, options);");
            });
        });
        AppendLine();
    }

    private void EmitBinaryStreamTypeAliasJsonConverter()
    {
        AppendBlock("file sealed class OpenApiGeneratedBinaryStreamTypeAliasJsonConverter<TAlias> : JsonConverter<TAlias>\n    where TAlias : struct, IOpenApiGeneratedTypeAlias<TAlias, Stream>", () =>
        {
            AppendLine("private static readonly OpenApiGeneratedBinaryStreamJsonConverter StreamConverter = new();");
            AppendLine();
            AppendBlock("public override TAlias Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)", () =>
            {
                AppendLine("Stream stream = StreamConverter.Read(ref reader, typeof(Stream), options) ?? new MemoryStream();");
                AppendLine("return TAlias.Create(stream);");
            });
            AppendLine();
            AppendBlock("public override void Write(Utf8JsonWriter writer, TAlias value, JsonSerializerOptions options)", () =>
            {
                AppendLine("StreamConverter.Write(writer, value.Value, options);");
            });
        });
        AppendLine();
    }

    #region Inline Enum Resolution

    /// <summary>
    /// Collects all inline enum properties across all schemas, deduplicates
    /// matching enums (same type name and same values), and differentiates
    /// conflicting ones (same type name, different values) by prefixing
    /// with the enclosing schema's type name.
    /// Returns a map of (schemaName, propertyName) → resolved enum type name.
    /// </summary>
    private Dictionary<(string SchemaName, string PropertyName), string> ResolveInlineEnums(Dictionary<string, string> typeNameMap)
    {
        var result = new Dictionary<(string, string), string>();

        // Collect all inline enums: (schemaName, propertyName, enumTypeName, enumValues, schema)
        var inlineEnums = new List<(string SchemaName, string PropertyName, string EnumTypeName, List<string> Values, IOpenApiSchema Schema)>();

        foreach ((string? schemaName, IOpenApiSchema? schema) in _allSchemas)
        {
            // If this schema is a variant of a discriminated union, its discriminator
            // property is handled by the polymorphic serializer and skipped in EmitRecord.
            // Don't collect it as an inline enum — it would be emitted but never referenced.
            string? skipDiscriminator = null;
            if (_unionVariantBaseTypes.TryGetValue(schema, out (string BaseTypeName, string DiscriminatorPropertyName) unionInfo))
            {
                skipDiscriminator = unionInfo.DiscriminatorPropertyName;
            }

            Dictionary<string, IOpenApiSchema> properties = CollectProperties(schema);
            foreach ((string? propName, IOpenApiSchema? propSchema) in properties)
            {
                if (skipDiscriminator != null && string.Equals(propName, skipDiscriminator, StringComparison.Ordinal))
                {
                    continue;
                }

                if (TypeResolver.IsEnum(propSchema) && !_knownSchemas.Contains(propSchema))
                {
                    string enumTypeName = NameHelper.ToPropertyName(propName, typeNameMap.GetValueOrDefault(schemaName));
                    List<string> values = ExtractEnumValues(propSchema);
                    inlineEnums.Add((schemaName, propName, enumTypeName, values, propSchema));
                }
            }
        }

        // Group by would-be enum type name
        var groups = inlineEnums
            .GroupBy(e => e.EnumTypeName)
            .ToList();

        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        // Reserve top-level schema type names to avoid conflicts
        foreach (string tn in typeNameMap.Values)
        {
            usedNames.Add(tn);
        }

        foreach (IGrouping<string, (string SchemaName, string PropertyName, string EnumTypeName, List<string> Values, IOpenApiSchema Schema)> group in groups)
        {
            string baseName = group.Key;

            // Sub-group by enum values (identical value lists share a name)
            var valueGroups = group
                .GroupBy(e => string.Join("|", e.Values))
                .ToList();

            if (valueGroups.Count == 1)
            {
                // All inline enums with this name have identical values → single enum
                string resolvedName = NameHelper.ApplyTypePrefix(baseName, _options.ModelPrefix);
                if (usedNames.Contains(resolvedName))
                {
                    // Conflict with a top-level type; differentiate
                    resolvedName = FindUniqueName(resolvedName, usedNames);
                }
                usedNames.Add(resolvedName);
                foreach ((string SchemaName, string PropertyName, string EnumTypeName, List<string> Values, IOpenApiSchema Schema) in valueGroups[0])
                {
                    result[(SchemaName, PropertyName)] = resolvedName;
                }
            }
            else
            {
                // Conflicting values → differentiate each value group
                foreach (IGrouping<string, (string SchemaName, string PropertyName, string EnumTypeName, List<string> Values, IOpenApiSchema Schema)> valueGroup in valueGroups)
                {
                    // Use the first entry's enclosing schema name as prefix
                    (string SchemaName, string PropertyName, string EnumTypeName, List<string> Values, IOpenApiSchema Schema) = valueGroup.First();
                    string schemaTypeName = typeNameMap.GetValueOrDefault(SchemaName, SchemaName);
                    string candidateName = schemaTypeName + baseName;
                    if (usedNames.Contains(candidateName))
                    {
                        candidateName = FindUniqueName(candidateName, usedNames);
                    }
                    usedNames.Add(candidateName);
                    foreach ((string SchemaName, string PropertyName, string EnumTypeName, List<string> Values, IOpenApiSchema Schema) entry in valueGroup)
                    {
                        result[(entry.SchemaName, entry.PropertyName)] = candidateName;
                    }
                }
            }
        }

        return result;
    }

    /// <summary>
    /// Emits the deduplicated inline enums. Each unique enum type name is emitted
    /// exactly once using the first matching schema as the source.
    /// </summary>
    private void EmitResolvedInlineEnums(
        Dictionary<(string SchemaName, string PropertyName), string> inlineEnumMap)
    {
        // Collect unique (resolvedName → schema) pairs, emit once each
        var emitted = new HashSet<string>(StringComparer.Ordinal);

        foreach (((string schemaName, string propertyName), string resolvedName) in inlineEnumMap)
        {
            if (!emitted.Add(resolvedName))
            {
                continue; // already emitted
            }

            // Find the inline enum schema
            Dictionary<string, IOpenApiSchema> properties = CollectProperties(_allSchemas[schemaName]);
            if (properties.TryGetValue(propertyName, out IOpenApiSchema? enumSchema))
            {
                EmitEnum(propertyName, enumSchema, resolvedName);
            }
        }
    }

    /// <summary>
    /// Extracts the raw enum values from a schema as a normalized list of strings.
    /// </summary>
    private static List<string> ExtractEnumValues(IOpenApiSchema schema)
    {
        return schema.Enum!
            .Where(e => e is null || !JsonNullSentinel.IsJsonNullSentinel(e))
            .Select(e =>
            {
                if (e is JsonValue jv)
                {
                    if (jv.TryGetValue(out string? s))
                    {
                        return s;
                    }

                    if (jv.TryGetValue(out int i))
                    {
                        return i.ToString(CultureInfo.InvariantCulture);
                    }

                    if (jv.TryGetValue(out long l))
                    {
                        return l.ToString(CultureInfo.InvariantCulture);
                    }

                    if (jv.TryGetValue(out double d))
                    {
                        return d.ToString(CultureInfo.InvariantCulture);
                    }
                }
                return e?.ToString() ?? "Unknown";
            })
            .ToList();
    }

    private static string FindUniqueName(string baseName, HashSet<string> usedNames)
    {
        int suffix = 2;
        string candidate = baseName + suffix;
        while (usedNames.Contains(candidate))
        {
            suffix++;
            candidate = baseName + suffix;
        }
        return candidate;
    }

    #endregion

    #region Inline Object Hoisting

    /// <summary>
    /// Discovers inline object schemas (object schemas with properties defined
    /// directly on a property rather than via $ref to a named component) and
    /// hoists them into synthesized named types. Each discovered inline object
    /// is registered with the <see cref="TypeResolver"/> so that type resolution
    /// returns the synthesized name instead of "object", and added to
    /// <see cref="_allSchemas"/> so it is emitted as a C# record.
    /// </summary>
    private void ResolveInlineObjects(Dictionary<string, string> typeNameMap)
    {
        var usedNames = new HashSet<string>(typeNameMap.Values, StringComparer.Ordinal);
        var visited = new HashSet<IOpenApiSchema>(ReferenceEqualityComparer.Instance);

        // Snapshot the original schema keys before adding hoisted inline objects.
        var originalKeys = _allSchemas.Keys.ToList();

        foreach (string schemaKey in originalKeys)
        {
            IOpenApiSchema schema = _allSchemas[schemaKey];
            string enclosingTypeName = typeNameMap.GetValueOrDefault(schemaKey, schemaKey);
            DiscoverInlineObjects(schema, enclosingTypeName, typeNameMap, usedNames, visited);
        }
    }

    private void DiscoverInlineObjects(
        IOpenApiSchema schema,
        string enclosingTypeName,
        Dictionary<string, string> typeNameMap,
        HashSet<string> usedNames,
        HashSet<IOpenApiSchema> visited)
    {
        if (!visited.Add(schema))
        {
            return;
        }

        Dictionary<string, IOpenApiSchema> properties = CollectProperties(schema);

        foreach ((string propName, IOpenApiSchema propSchema) in properties)
        {
            string? hoistedName = TryHoistPropertySchema(propSchema, enclosingTypeName, propName, typeNameMap, usedNames, visited);

            // If the property itself wasn't hoisted, check array items and additionalProperties
            if (hoistedName == null)
            {
                if (TypeResolver.HasTypeFlag(propSchema, JsonSchemaType.Array) && propSchema.Items is { } items)
                {
                    TryHoistPropertySchema(items, enclosingTypeName, propName, typeNameMap, usedNames, visited);
                }

                if (propSchema.AdditionalProperties is { } addProps)
                {
                    TryHoistPropertySchema(addProps, enclosingTypeName, propName, typeNameMap, usedNames, visited);
                }
            }
        }

        // Scan the schema's own AdditionalProperties (JsonExtensionData value type)
        if (schema.AdditionalProperties is { } ownAddProps && (schema.Properties == null || schema.Properties.Count == 0))
        {
            TryHoistPropertySchema(ownAddProps, enclosingTypeName, "Value", typeNameMap, usedNames, visited);
        }

        // Scan oneOf/anyOf variants for inline objects (handles component-level union schemas
        // where variants include inline object definitions that need to be hoisted).
        // Skip when the schema has its own direct properties — in that case the schema is
        // emitted as a record and the oneOf/anyOf is not consumed, so hoisting would
        // produce orphan types.
        IList<IOpenApiSchema>? rawUnionVariants = schema.OneOf ?? schema.AnyOf;
        if (rawUnionVariants != null && properties.Count == 0)
        {
            // Filter null-type variants to keep variant numbering sequential.
            IEnumerable<IOpenApiSchema> unionVariants =
                rawUnionVariants.Where(s => !(s.Type.HasValue && s.Type.Value == JsonSchemaType.Null));

            bool isDiscriminated = schema.Discriminator is { PropertyName: not null };
            string? discPropName = schema.Discriminator?.PropertyName;

            int variantIndex = 1;
            foreach (IOpenApiSchema variant in unionVariants)
            {
                if (variant is not OpenApiSchemaReference && !_knownSchemas.Contains(variant))
                {
                    // Try to hoist inline objects within union variants
                    string variantPropName = $"Variant{variantIndex}";
                    TryHoistPropertySchema(variant, enclosingTypeName, variantPropName, typeNameMap, usedNames, visited);

                    // For discriminated unions, record the union base type so the hoisted
                    // inline variant can inherit from it (required for polymorphic deserialization).
                    if (isDiscriminated)
                    {
                        _unionVariantBaseTypes.TryAdd(variant, (enclosingTypeName, discPropName!));
                    }
                }
                else if (isDiscriminated && variant is OpenApiSchemaReference refVariant && refVariant.Reference?.Id != null)
                {
                    // For $ref variants in discriminated unions, record the union base type
                    // on the referenced schema so it inherits from the union.
                    if (_allSchemas.TryGetValue(refVariant.Reference.Id, out IOpenApiSchema? refSchema))
                    {
                        _unionVariantBaseTypes.TryAdd(refSchema, (enclosingTypeName, discPropName!));
                    }
                }

                variantIndex++;
            }
        }
    }

    /// <summary>
    /// Checks if a property schema is an inline object, allOf composition, or oneOf/anyOf
    /// union of $refs, and if so hoists it to a named type. Returns the synthesized type
    /// name if hoisted, null otherwise.
    /// </summary>
    private string? TryHoistPropertySchema(
        IOpenApiSchema propSchema,
        string enclosingTypeName,
        string propName,
        Dictionary<string, string> typeNameMap,
        HashSet<string> usedNames,
        HashSet<IOpenApiSchema> visited)
    {
        if (IsInlineObject(propSchema))
        {
            string inlineTypeName = SynthesizeInlineTypeName(enclosingTypeName, propName, usedNames);
            HoistInlineObject(propSchema, inlineTypeName, typeNameMap, usedNames);
            DiscoverInlineObjects(propSchema, inlineTypeName, typeNameMap, usedNames, visited);
            return inlineTypeName;
        }

        if (IsInlineAllOfComposition(propSchema))
        {
            string inlineTypeName = SynthesizeInlineTypeName(enclosingTypeName, propName, usedNames);
            HoistInlineObject(propSchema, inlineTypeName, typeNameMap, usedNames);
            DiscoverInlineObjects(propSchema, inlineTypeName, typeNameMap, usedNames, visited);
            return inlineTypeName;
        }

        if (IsInlineUnion(propSchema))
        {
            string inlineTypeName = SynthesizeInlineTypeName(enclosingTypeName, propName, usedNames);

            bool isDiscriminated = propSchema.Discriminator is { PropertyName: not null };
            string? discPropName = propSchema.Discriminator?.PropertyName;

            // Hoist any inline object variants within the union before hoisting the union itself.
            // This ensures the inline objects are registered with TypeResolver and emitted as records.
            // Filter out null-type variants (from nullable [type, null] patterns) to
            // keep variant numbering sequential, consistent with IsInlineUnion's filtering.
            IList<IOpenApiSchema>? rawVariants = propSchema.OneOf ?? propSchema.AnyOf;
            if (rawVariants != null)
            {
                IEnumerable<IOpenApiSchema> variants =
                    rawVariants.Where(s => !(s.Type.HasValue && s.Type.Value == JsonSchemaType.Null));
                int variantIndex = 1;
                foreach (IOpenApiSchema variant in variants)
                {
                    if (IsInlineObject(variant))
                    {
                        string variantTypeName = SynthesizeInlineTypeName(inlineTypeName, $"Variant{variantIndex}", usedNames);
                        HoistInlineObject(variant, variantTypeName, typeNameMap, usedNames);
                        DiscoverInlineObjects(variant, variantTypeName, typeNameMap, usedNames, visited);

                        if (isDiscriminated)
                        {
                            _unionVariantBaseTypes.TryAdd(variant, (inlineTypeName, discPropName!));
                        }
                    }
                    else if (isDiscriminated && variant is OpenApiSchemaReference refVariant && refVariant.Reference?.Id != null)
                    {
                        if (_allSchemas.TryGetValue(refVariant.Reference.Id, out IOpenApiSchema? refSchema))
                        {
                            _unionVariantBaseTypes.TryAdd(refSchema, (inlineTypeName, discPropName!));
                        }
                    }

                    variantIndex++;
                }
            }

            HoistInlineObject(propSchema, inlineTypeName, typeNameMap, usedNames);
            return inlineTypeName;
        }

        return null;
    }

    private void HoistInlineObject(
        IOpenApiSchema schema,
        string typeName,
        Dictionary<string, string> typeNameMap,
        HashSet<string> usedNames)
    {
        _typeResolver.RegisterInlineObjectType(schema, typeName);
        _allSchemas[typeName] = schema;
        _knownSchemas.Add(schema);
        typeNameMap[typeName] = typeName;
        usedNames.Add(typeName);
    }

    private bool IsInlineObject(IOpenApiSchema schema)
    {
        // Skip $ref schemas — they already have a type name
        if (schema is OpenApiSchemaReference)
        {
            return false;
        }

        // Skip schemas that are already named component schemas (or already hoisted)
        if (_knownSchemas.Contains(schema))
        {
            return false;
        }

        // Skip enums — handled by the inline enum pass
        if (TypeResolver.IsEnum(schema))
        {
            return false;
        }

        // Skip composition schemas — handled by IsInlineAllOfComposition / IsInlineRefUnion
        if (schema.AllOf is { Count: > 0 } ||
            schema.OneOf is { Count: > 0 } ||
            schema.AnyOf is { Count: > 0 })
        {
            return false;
        }

        // Must have properties to be an inline object
        if (schema.Properties is not { Count: > 0 })
        {
            return false;
        }

        return true;
    }

    /// <summary>
    /// Detects an inline allOf composition (no $ref member) that has properties
    /// via one of its members — should be hoisted as a record.
    /// </summary>
    private bool IsInlineAllOfComposition(IOpenApiSchema schema)
    {
        // Skip $ref schemas
        if (schema is OpenApiSchemaReference)
        {
            return false;
        }

        // Skip already known schemas
        if (_knownSchemas.Contains(schema))
        {
            return false;
        }

        if (schema.AllOf is not { Count: > 0 })
        {
            return false;
        }

        // Must NOT have a single $ref member (that's inheritance, handled by ResolveAllOf)
        if (schema.AllOf.OfType<OpenApiSchemaReference>().Any())
        {
            return false;
        }

        // At least one member must have properties
        return schema.AllOf.Any(s => s.Properties is { Count: > 0 });
    }

    /// <summary>
    /// Detects an inline oneOf/anyOf where all variants are $refs or inline objects —
    /// should be hoisted as an abstract record with [JsonDerivedType] attributes.
    /// Inline object variants are hoisted to named records before the union is hoisted.
    /// </summary>
    private bool IsInlineUnion(IOpenApiSchema schema)
    {
        // Skip $ref schemas
        if (schema is OpenApiSchemaReference)
        {
            return false;
        }

        // Skip already known schemas
        if (_knownSchemas.Contains(schema))
        {
            return false;
        }

        IList<IOpenApiSchema>? variants = schema.OneOf ?? schema.AnyOf;
        if (variants is null or { Count: 0 })
        {
            return false;
        }

        // Filter out null-type variants (from nullable [type, null] patterns)
        if (schema.OneOf is { } oneOf)
        {
            var nonNull = oneOf.Where(s =>
                !(s.Type.HasValue && s.Type.Value == JsonSchemaType.Null)).ToList();
            if (nonNull.Count != oneOf.Count)
            {
                variants = nonNull;
            }
        }
        else if (schema.AnyOf is { } anyOf)
        {
            var nonNull = anyOf.Where(s =>
                !(s.Type.HasValue && s.Type.Value == JsonSchemaType.Null)).ToList();
            if (nonNull.Count == 1)
            {
                return false; // single non-null variant — resolved directly
            }
            variants = nonNull;
        }

        if (variants.Count < 2)
        {
            return false;
        }

        // All variants must be $refs or inline objects (hoistable to records)
        return variants.All(v => v is OpenApiSchemaReference || IsInlineObject(v));
    }

    private static string SynthesizeInlineTypeName(string enclosingTypeName, string propName, HashSet<string> usedNames)
    {
        string pascalProp = NameHelper.ToPropertyName(propName);
        string candidate = enclosingTypeName + pascalProp;

        if (!usedNames.Contains(candidate))
        {
            return candidate;
        }

        return FindUniqueName(candidate, usedNames);
    }

    #endregion

    private void EmitSchemaWithTypeName(string schemaName, IOpenApiSchema schema, string typeName)
    {
        if (TypeResolver.IsEnum(schema))
        {
            EmitEnum(schemaName, schema, typeName);
        }
        else if (ShouldEmitAsRecord(schema))
        {
            EmitRecord(schemaName, schema, typeName);
        }
        else if (TypeResolver.IsTypeAlias(schema))
        {
            if (!_options.InlinePrimitiveTypeAliases)
            {
                EmitTypeAlias(schemaName, schema, typeName);
            }
        }
        else if (schema.OneOf is { Count: > 0 } || schema.AnyOf is { Count: > 0 })
        {
            EmitUnionType(schemaName, schema, typeName);
        }
        else
        {
            // Fallback: emit as a record with no properties
            EmitDocComment(schema.Description);
            AppendLine($"public record {typeName};");
            AppendLine();
        }
    }

    private static bool ShouldEmitAsRecord(IOpenApiSchema schema)
    {
        // Direct properties
        if (schema.Properties is { Count: > 0 })
        {
            return true;
        }

        // allOf with at least one schema that has properties
        if (schema.AllOf is { Count: > 0 })
        {
            foreach (IOpenApiSchema sub in schema.AllOf)
            {
                if (sub.Properties is { Count: > 0 })
                {
                    return true;
                }

                if (sub is OpenApiSchemaReference)
                {
                    return true; // inheritance
                }
            }
        }

        // Object type with additionalProperties
        if (TypeResolver.HasTypeFlag(schema, JsonSchemaType.Object) && schema.AdditionalProperties != null)
        {
            return false; // handled as a dictionary alias
        }

        if (TypeResolver.HasTypeFlag(schema, JsonSchemaType.Object))
        {
            return true;
        }

        return false;
    }

    #region Enum Emission

    private void EmitEnum(string schemaName, IOpenApiSchema schema, string? typeNameOverride = null)
    {
        string typeName = typeNameOverride ?? NameHelper.ToTypeName(schemaName, _options.ModelPrefix);

        EmitDocComment(schema.Description);
        EmitObsoleteAttribute(schema);

        if (TypeResolver.HasTypeFlag(schema, JsonSchemaType.String))
        {
            AppendLine($"[JsonConverter(typeof(JsonStringEnumConverter<{typeName}>))]");
        }

        AppendBlock($"public enum {typeName}", () =>
        {
            var enumValues = schema.Enum!
                .Where(e => e is null || !JsonNullSentinel.IsJsonNullSentinel(e))
                .Select(e =>
                {
                    if (e is JsonValue jv)
                    {
                        if (jv.TryGetValue(out string? s))
                        {
                            return s;
                        }

                        if (jv.TryGetValue(out int i))
                        {
                            return i.ToString(CultureInfo.InvariantCulture);
                        }

                        if (jv.TryGetValue(out long l))
                        {
                            return l.ToString(CultureInfo.InvariantCulture);
                        }

                        if (jv.TryGetValue(out double d))
                        {
                            return d.ToString(CultureInfo.InvariantCulture);
                        }
                    }
                    return e?.ToString() ?? "Unknown";
                })
                .ToList();

            // Resolve duplicate enum member names by appending numeric suffixes
            var memberNames = new string[enumValues.Count];
            var usedMemberNames = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < enumValues.Count; i++)
            {
                string baseName = NameHelper.ToEnumMemberName(enumValues[i]);
                string memberName = baseName;
                int suffix = 2;
                while (usedMemberNames.Contains(memberName))
                {
                    memberName = baseName + suffix;
                    suffix++;
                }
                usedMemberNames.Add(memberName);
                memberNames[i] = memberName;
            }

            for (int i = 0; i < enumValues.Count; i++)
            {
                string rawValue = enumValues[i];
                string memberName = memberNames[i];
                bool isLast = i == enumValues.Count - 1;

                if (TypeResolver.HasTypeFlag(schema, JsonSchemaType.String))
                {
                    AppendLine($"[JsonStringEnumMemberName(\"{EscapeCSharpStringLiteral(rawValue)}\")]");
                }

                if ((TypeResolver.HasTypeFlag(schema, JsonSchemaType.Integer) || TypeResolver.HasTypeFlag(schema, JsonSchemaType.Number))
                    && double.TryParse(rawValue, NumberStyles.Any, CultureInfo.InvariantCulture, out _))
                {
                    Append($"{memberName} = {rawValue}");
                }
                else
                {
                    Append($"{memberName}");
                }

                AppendLineRaw(isLast ? "" : ",");
            }
        });
        AppendLine();
    }

    #endregion

    #region Record Emission

    private void EmitRecord(string schemaName, IOpenApiSchema schema, string? typeNameOverride = null)
    {
        string typeName = typeNameOverride ?? NameHelper.ToTypeName(schemaName, _options.ModelPrefix);

        // Collect all properties (including from allOf)
        Dictionary<string, IOpenApiSchema> properties = CollectProperties(schema);
        HashSet<string> requiredProps = CollectRequired(schema);

        // Determine base type from allOf $ref
        string? baseType = null;
        HashSet<string>? basePropertyNames = null;
        if (schema.AllOf is { Count: > 0 })
        {
            OpenApiSchemaReference? refSchema = schema.AllOf.OfType<OpenApiSchemaReference>().FirstOrDefault();
            if (refSchema?.Reference?.Id != null)
            {
                baseType = NameHelper.ToTypeName(refSchema.Reference.Id, _options.ModelPrefix);
                basePropertyNames = CollectBasePropertyNames(refSchema);
            }
        }

        // If no allOf base type, check if this schema is a variant of a discriminated
        // union. Variants must inherit from the union base type for polymorphic
        // deserialization (JsonDerivedType / JsonPolymorphic) to function.
        string? unionDiscriminatorPropertyName = null;
        if (baseType == null && _unionVariantBaseTypes.TryGetValue(schema, out (string BaseTypeName, string DiscriminatorPropertyName) unionInfo))
        {
            baseType = unionInfo.BaseTypeName;
            unionDiscriminatorPropertyName = unionInfo.DiscriminatorPropertyName;
        }

        EmitDocComment(schema.Description);
        EmitObsoleteAttribute(schema);

        string declaration = baseType != null
            ? $"public partial record {typeName} : {baseType}"
            : $"public partial record {typeName}";

        AppendBlock(declaration, () =>
        {
            // Filter out properties already defined in a base type
            var filteredProps = properties
                .Where(p => basePropertyNames == null || !basePropertyNames.Contains(p.Key))
                .ToList();

            // When inheriting from a discriminated union, skip the discriminator property
            // on the derived type — it is handled by the polymorphic serializer.
            if (unionDiscriminatorPropertyName != null)
            {
                filteredProps = filteredProps
                    .Where(p => !string.Equals(p.Key, unionDiscriminatorPropertyName, StringComparison.Ordinal))
                    .ToList();
            }

            // Two-pass property name resolution: detect collisions, assign clean names to
            // the most natural property name, differentiate others meaningfully.
            Dictionary<string, string> propertyNameMap = ResolvePropertyNameCollisions(filteredProps.Select(p => p.Key), typeName);

            foreach ((string? propName, IOpenApiSchema? propSchema) in filteredProps)
            {
                EmitProperty(propName, propSchema, requiredProps.Contains(propName), schemaName, typeName, propertyNameMap[propName]);
            }

            // If object has additionalProperties alongside regular properties
            if (schema.AdditionalProperties is { } additionalProps &&
                schema.Properties is { Count: > 0 })
            {
                string valueType = _typeResolver.Resolve(additionalProps);
                string dictType = _options.UseImmutableDictionaries ? "IReadOnlyDictionary" : "Dictionary";
                AppendLine();

                AppendLine("[JsonExtensionData]");

                AppendLine($"public {dictType}<string, {valueType}>? AdditionalProperties {{ get; init; }}");
            }
        });
        AppendLine();
    }

    private void EmitProperty(string propertyName, IOpenApiSchema propertySchema, bool isRequired, string? schemaName = null, string? enclosingTypeName = null, string? csharpNameOverride = null)
    {
        EmitDocComment(propertySchema.Description);
        EmitObsoleteAttribute(propertySchema);

        string csharpPropertyName = csharpNameOverride ?? NameHelper.ToPropertyName(propertyName, enclosingTypeName);
        string? jsonName = NameHelper.GetJsonPropertyName(propertyName, csharpPropertyName);

        // Resolve the type
        string typeName;
        if (TypeResolver.IsEnum(propertySchema) && !_knownSchemas.Contains(propertySchema))
        {
            // Inline enum — look up the resolved enum type name from the
            // pre-computed inline enum map (handles dedup & conflict resolution).
            string enumTypeName = csharpPropertyName; // fallback
            if (schemaName != null)
            {
                (string schemaName, string propertyName) key = (schemaName, propertyName);
                if (_inlineEnumMap.TryGetValue(key, out string? resolved))
                {
                    enumTypeName = resolved;
                }
            }

            typeName = isRequired ? enumTypeName : enumTypeName + "?";
        }
        else
        {
            typeName = _typeResolver.ResolveWithNullability(propertySchema, isRequired);
        }

        // Add validation attributes
        EmitValidationAttributes(propertySchema);

        // Add JSON attribute
        if (!_options.OmitJsonPropertyNameAttributes && jsonName != null)
        {
            AppendLine($"[JsonPropertyName(\"{EscapeCSharpStringLiteral(jsonName)}\")]");
        }

        if (_typeResolver.IsBinaryStreamPropertyType(propertySchema))
        {
            AppendLine("[JsonConverter(typeof(OpenApiGeneratedBinaryStreamJsonConverter))]");
        }

        // Resolve the C# default value literal (if any)
        string? defaultLiteral = ToCSharpDefaultLiteral(propertySchema, typeName);
        string defaultSuffix = defaultLiteral != null ? $" = {defaultLiteral};" : "";

        // Add required keyword for required properties
        if (isRequired)
        {
            AppendLine($"public required {typeName} {csharpPropertyName} {{ get; init; }}{defaultSuffix}");
        }
        else
        {
            AppendLine($"public {typeName} {csharpPropertyName} {{ get; init; }}{defaultSuffix}");
        }

        AppendLine();
    }

    /// <summary>
    /// Converts an OpenAPI schema's default value to a C# literal string.
    /// Returns null when no default is specified or the default cannot be represented.
    /// </summary>
    private string? ToCSharpDefaultLiteral(IOpenApiSchema schema, string resolvedTypeName)
    {
        if (schema.Default is not JsonNode defaultNode)
        {
            return null;
        }

        if (!_options.AddDefaultValuesToProperties)
        {
            return "null!"; // Return null to avoid warnings in code.
        }

        // Strip trailing '?' from nullable types for matching purposes
        string baseTypeName = resolvedTypeName.TrimEnd('?');

        if (defaultNode is JsonValue jv)
        {
            // Boolean
            if (jv.TryGetValue(out bool boolVal))
            {
                return boolVal ? "true" : "false";
            }

            // String-based types
            if (jv.TryGetValue(out string? strVal))
            {
                // Inline or top-level enum: convert to EnumType.MemberName
                if (TypeResolver.IsEnum(schema) || IsEnumTypeName(baseTypeName))
                {
                    string memberName = NameHelper.ToEnumMemberName(strVal);
                    return $"{_options.Namespace}.{baseTypeName}.{memberName}";
                }

                if (string.IsNullOrEmpty(schema.Format))
                {
                    return $"\"{EscapeCSharpStringLiteral(strVal)}\"";
                }

                if (schema.Format == "date-time" && DateTimeOffset.TryParse(strVal, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out DateTimeOffset dto))
                {
                    return $"DateTimeOffset.Parse(\"{dto.ToString("O", CultureInfo.InvariantCulture)}\", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind)";
                }

                if (schema.Format == "date" && DateOnly.TryParse(strVal, CultureInfo.InvariantCulture, DateTimeStyles.None, out DateOnly dateOnly))
                {
                    return $"DateOnly.ParseExact(\"{dateOnly:yyyy-MM-dd}\", \"yyyy-MM-dd\", CultureInfo.InvariantCulture)";
                }

                if (schema.Format == "time" && TimeOnly.TryParse(strVal, CultureInfo.InvariantCulture, DateTimeStyles.None, out TimeOnly timeOnly))
                {
                    return $"TimeOnly.Parse(\"{timeOnly.ToString("O", CultureInfo.InvariantCulture)}\", CultureInfo.InvariantCulture)";
                }

                if (schema.Format == "uuid" && Guid.TryParse(strVal, out Guid guid))
                {
                    return $"Guid.Parse(\"{guid}\")";
                }

                if (schema.Format == "uri" && Uri.TryCreate(strVal, UriKind.Absolute, out Uri? uri))
                {
                    return $"new Uri(\"{EscapeCSharpStringLiteral(uri.ToString())}\")";
                }

                return "null!";
            }

            // Integer types
            if (jv.TryGetValue(out int intVal))
            {
                return intVal.ToString(CultureInfo.InvariantCulture);
            }

            if (jv.TryGetValue(out long longVal))
            {
                return baseTypeName switch
                {
                    "long" => longVal.ToString(CultureInfo.InvariantCulture) + "L",
                    _ => longVal.ToString(CultureInfo.InvariantCulture)
                };
            }

            // Floating-point types
            if (jv.TryGetValue(out double dblVal))
            {
                return baseTypeName switch
                {
                    "float" => dblVal.ToString(CultureInfo.InvariantCulture) + "f",
                    "decimal" => dblVal.ToString(CultureInfo.InvariantCulture) + "m",
                    _ => dblVal.ToString(CultureInfo.InvariantCulture) + "d"
                };
            }
        }

        // Arrays: emit as empty collection
        if (defaultNode is JsonArray)
        {
            return "[]";
        }

        return null;
    }

    /// <summary>
    /// Checks whether a resolved type name corresponds to an enum (either a top-level
    /// schema enum or an inline enum registered in the inline enum map).
    /// </summary>
    private bool IsEnumTypeName(string typeName)
    {
        // Check top-level schemas for a matching enum
        foreach ((string? name, IOpenApiSchema? schema) in _allSchemas)
        {
            if (NameHelper.ToTypeName(name, _options.ModelPrefix) == typeName && TypeResolver.IsEnum(schema))
            {
                return true;
            }
        }

        // Check inline enum map
        return _inlineEnumMap.ContainsValue(typeName);
    }

    #endregion

    #region Type Alias Emission

    private void EmitTypeAlias(string schemaName, IOpenApiSchema schema, string? typeNameOverride = null)
    {
        string typeName = typeNameOverride ?? NameHelper.ToTypeName(schemaName, _options.ModelPrefix);
        string resolvedType = _typeResolver.ResolveUnderlyingType(schema);

        EmitDocComment(schema.Description);

        // C# doesn't have direct type aliases at the top level.
        // We emit a global using alias or a wrapper record.
        // For simplicity and usability, emit a readonly record struct wrapping the value.
        AppendLine($"/// <summary>");
        AppendLine($"/// Type alias for {resolvedType}.");
        AppendLine($"/// </summary>");

        EmitObsoleteAttribute(schema);

        if (!_options.InlinePrimitiveTypeAliases)
        {
            string converterType = _typeResolver.IsBinaryStreamPropertyType(schema)
                ? $"OpenApiGeneratedBinaryStreamTypeAliasJsonConverter<{typeName}>"
                : $"OpenApiGeneratedTypeAliasJsonConverter<{typeName}, {resolvedType}>";

            AppendLine($"[JsonConverter(typeof({converterType}))]");
        }

        AppendBlock($"public readonly partial record struct {typeName}({resolvedType} Value) : IOpenApiGeneratedTypeAlias<{typeName}, {resolvedType}>", () =>
        {
            AppendLine($"public static {typeName} Create({resolvedType} value) => new(value);");
        });
        AppendLine();
    }

    #endregion

    #region Union Type Emission

    private void EmitUnionType(string schemaName, IOpenApiSchema schema, string? typeNameOverride = null)
    {
        string typeName = typeNameOverride ?? NameHelper.ToTypeName(schemaName, _options.ModelPrefix);
        IList<IOpenApiSchema> variants = schema.OneOf ?? schema.AnyOf ?? [];

        EmitDocComment(schema.Description);
        EmitObsoleteAttribute(schema);

        if (schema.Discriminator is { PropertyName: not null } disc)
        {
            // Emit discriminated union using JsonDerivedType
            EmitDiscriminatedUnion(typeName, variants, disc);
        }
        else
        {
            // Emit as a marker interface / abstract record
            EmitSimpleUnion(typeName, variants);
        }
    }

    private void EmitDiscriminatedUnion(
        string typeName,
        IList<IOpenApiSchema> variants,
        OpenApiDiscriminator discriminator)
    {
        // Build mapping: discriminator value → type name
        var mapping = new Dictionary<string, string>();
        if (discriminator.Mapping is { Count: > 0 })
        {
            foreach ((string? key, OpenApiSchemaReference? schemaRef) in discriminator.Mapping)
            {
                mapping[key] = NameHelper.ToTypeName(schemaRef.Reference.Id, _options.ModelPrefix);
            }
        }
        else
        {
            // Infer mapping from $ref names
            foreach (IOpenApiSchema variant in variants)
            {
                if (variant is OpenApiSchemaReference variantRef)
                {
                    string? name = variantRef.Reference.Id;

                    if (name is null)
                    {
                        continue;
                    }

                    mapping[name] = NameHelper.ToTypeName(name, _options.ModelPrefix);
                }
            }
        }

        // Add hoisted inline object variants not covered by the discriminator mapping.
        // The discriminator value is extracted from the variant's discriminator property
        // (e.g., petType: "dog"). Falls back to the synthesized type name when no
        // discriminator property value is found.
        foreach (IOpenApiSchema variant in variants)
        {
            if (variant is OpenApiSchemaReference)
            {
                continue;
            }

            string? hoistedName = _typeResolver.GetInlineObjectTypeName(variant);
            if (hoistedName is null || mapping.ContainsValue(hoistedName))
            {
                continue;
            }

            string discriminatorValue = TryGetDiscriminatorValue(variant, discriminator.PropertyName!) ?? hoistedName;
            if (mapping.ContainsKey(discriminatorValue))
            {
                continue;
            }

            mapping[discriminatorValue] = hoistedName;
        }

        foreach ((string? discriminatorValue, string? derivedType) in mapping)
        {
            AppendLine($"[JsonDerivedType(typeof({derivedType}), \"{discriminatorValue}\")]");
        }

        AppendLine($"[JsonPolymorphic(TypeDiscriminatorPropertyName = \"{discriminator.PropertyName}\")]");

        AppendLine($"public abstract partial record {typeName};");
        AppendLine();
    }

    /// <summary>
    /// Extracts the wire discriminator value from an inline variant's discriminator property.
    /// In OpenAPI 3.0 the value is expressed via <see cref="OpenApiSchema.Enum"/> (a single
    /// <see cref="JsonValue"/>); in OpenAPI 3.1 it is expressed via <see cref="OpenApiSchema.Const"/>.
    /// Returns null if neither is found.
    /// </summary>
    private static string? TryGetDiscriminatorValue(IOpenApiSchema variant, string discriminatorPropertyName)
    {
        Dictionary<string, IOpenApiSchema> properties = CollectProperties(variant);
        if (!properties.TryGetValue(discriminatorPropertyName, out IOpenApiSchema? discProp))
        {
            return null;
        }

        if (!string.IsNullOrEmpty(discProp.Const))
        {
            return discProp.Const;
        }

        if (discProp.Enum is null || discProp.Enum.Count == 0)
        {
            return null;
        }

        foreach (var enumValue in discProp.Enum)
        {
            if (enumValue is JsonValue jv && jv.TryGetValue(out string? s))
            {
                return s;
            }
        }

        return null;
    }

    private void EmitSimpleUnion(string typeName, IList<IOpenApiSchema> variants)
    {
        // Filter out null-type variants (from nullable anyOf patterns like [type, null])
        var nonNullVariants = variants
            .Where(v => !(v.Type.HasValue && v.Type.Value == JsonSchemaType.Null))
            .ToList();

        // Collect the variant type names for documentation
        var variantNames = new List<string>();
        foreach (IOpenApiSchema variant in nonNullVariants)
        {
            if (variant is OpenApiSchemaReference refVariant)
            {
                variantNames.Add(NameHelper.ToTypeName(refVariant.Reference.Id, _options.ModelPrefix));
            }
            else
            {
                string? hoistedName = _typeResolver.GetInlineObjectTypeName(variant);
                if (hoistedName != null)
                {
                    variantNames.Add(hoistedName);
                }
            }
        }

        bool hasInlineVariant = nonNullVariants.Any(v => v is not OpenApiSchemaReference && _typeResolver.GetInlineObjectTypeName(v) != null);

        if (variantNames.Count > 0)
        {
            AppendLine($"/// <remarks>");
            AppendLine($"/// Union of: {string.Join(" | ", variantNames)}");
            if (hasInlineVariant)
            {
                AppendLine("/// Inline object variants use the synthesized type name as the discriminator value.");
            }
            AppendLine($"/// </remarks>");
        }

        // Emit [JsonDerivedType] for each resolvable variant
        foreach (IOpenApiSchema variant in nonNullVariants)
        {
            if (variant is OpenApiSchemaReference refVariant)
            {
                string derivedName = NameHelper.ToTypeName(refVariant.Reference.Id, _options.ModelPrefix);
                AppendLine($"[JsonDerivedType(typeof({derivedName}), \"{refVariant.Reference.Id}\")]");
            }
            else
            {
                string? hoistedName = _typeResolver.GetInlineObjectTypeName(variant);
                if (hoistedName != null)
                {
                    AppendLine($"[JsonDerivedType(typeof({hoistedName}), \"{hoistedName}\")]");
                }
            }
        }

        AppendLine($"public abstract partial record {typeName};");
        AppendLine();
    }

    #endregion

    #region Name Collision Resolution

    /// <summary>
    /// Resolves type name collisions across all schemas using a two-pass approach.
    /// In each collision group, the most "natural" schema name keeps the clean PascalCase
    /// type name, and others get meaningfully differentiated names.
    /// </summary>
    private Dictionary<string, string> ResolveTypeNameCollisions(IEnumerable<string> schemaNames)
    {
        var result = new Dictionary<string, string>();
        var usedNames = new HashSet<string>(StringComparer.Ordinal);

        // Group schema names by their PascalCase type name
        var groups = schemaNames
            .Select(name => (Original: name, PascalName: NameHelper.ToTypeName(name, prefix: null)))
            .GroupBy(x => x.PascalName)
            .ToList();

        foreach (IGrouping<string, (string Original, string PascalName)>? group in groups)
        {
            string pascalName = group.Key;
            var members = group.ToList();

            if (members.Count == 1)
            {
                result[members[0].Original] = NameHelper.ApplyTypePrefix(pascalName, _options.ModelPrefix);
                usedNames.Add(pascalName);
                continue;
            }

            // Sort by naturalness: most natural name keeps the clean PascalCase
            var sorted = members.OrderBy(m => NameHelper.NaturalnessScore(m.Original, pascalName)).ToList();

            // Winner gets the clean name
            result[sorted[0].Original] = NameHelper.ApplyTypePrefix(pascalName, _options.ModelPrefix);
            usedNames.Add(pascalName);

            // Others get differentiated names
            for (int i = 1; i < sorted.Count; i++)
            {
                string differentiated = NameHelper.ToDifferentiatedName(sorted[i].Original, pascalName, usedNames);
                result[sorted[i].Original] = NameHelper.ApplyTypePrefix(differentiated, _options.ModelPrefix);
                usedNames.Add(differentiated);
            }
        }

        return result;
    }

    /// <summary>
    /// Resolves property name collisions within a record using a two-pass approach.
    /// In each collision group, the most "natural" property name keeps the clean PascalCase
    /// name, and others get meaningfully differentiated names.
    /// </summary>
    private static Dictionary<string, string> ResolvePropertyNameCollisions(IEnumerable<string> propertyNames, string typeName)
    {
        var result = new Dictionary<string, string>();
        var usedNames = new HashSet<string>(StringComparer.Ordinal);

        // Group property names by their PascalCase form
        var groups = propertyNames
            .Select(name => (Original: name, PascalName: NameHelper.ToPropertyName(name, typeName)))
            .GroupBy(x => x.PascalName)
            .ToList();

        foreach (IGrouping<string, (string Original, string PascalName)>? group in groups)
        {
            string pascalName = group.Key;
            var members = group.ToList();

            if (members.Count == 1)
            {
                result[members[0].Original] = pascalName;
                usedNames.Add(pascalName);
                continue;
            }

            // Sort by naturalness: most natural name keeps the clean PascalCase
            var sorted = members.OrderBy(m => NameHelper.NaturalnessScore(m.Original, pascalName)).ToList();

            // Winner gets the clean name
            result[sorted[0].Original] = pascalName;
            usedNames.Add(pascalName);

            // Others get differentiated names
            for (int i = 1; i < sorted.Count; i++)
            {
                string differentiated = NameHelper.ToDifferentiatedName(sorted[i].Original, pascalName, usedNames);
                result[sorted[i].Original] = differentiated;
                usedNames.Add(differentiated);
            }
        }

        return result;
    }

    #endregion

    #region Helpers

    private static Dictionary<string, IOpenApiSchema> CollectProperties(IOpenApiSchema schema)
    {
        var result = new Dictionary<string, IOpenApiSchema>();

        // Properties from allOf subschemas (excluding $ref ones which become base types)
        if (schema.AllOf is { Count: > 0 })
        {
            foreach (IOpenApiSchema sub in schema.AllOf)
            {
                if (sub is OpenApiSchemaReference)
                {
                    continue; // Skip $ref entries, they become base types
                }

                if (sub.Properties != null)
                {
                    foreach ((string? name, IOpenApiSchema? prop) in sub.Properties)
                    {
                        result.TryAdd(name, prop);
                    }
                }
            }
        }

        // Direct properties
        if (schema.Properties != null)
        {
            foreach ((string? name, IOpenApiSchema? prop) in schema.Properties)
            {
                result.TryAdd(name, prop);
            }
        }

        return result;
    }

    /// <summary>
    /// Recursively collects all property names defined in a base type and its ancestors.
    /// Used to avoid re-declaring properties that would hide required base members (CS9031).
    /// </summary>
    private HashSet<string> CollectBasePropertyNames(IOpenApiSchema baseSchema)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);

        // Resolve references through our schema dictionary
        IOpenApiSchema resolved = baseSchema;
        if (baseSchema is OpenApiSchemaReference schemaRef
            && schemaRef.Reference?.Id is not null
            && _allSchemas.TryGetValue(schemaRef.Reference.Id, out IOpenApiSchema? lookedUp))
        {
            resolved = lookedUp;
        }

        // Collect direct properties
        if (resolved.Properties != null)
        {
            foreach (string name in resolved.Properties.Keys)
            {
                names.Add(name);
            }
        }

        // Recurse into allOf to collect ancestor properties
        if (resolved.AllOf is { Count: > 0 })
        {
            foreach (IOpenApiSchema sub in resolved.AllOf)
            {
                if (sub.Properties != null)
                {
                    foreach (string name in sub.Properties.Keys)
                    {
                        names.Add(name);
                    }
                }

                // Follow $ref to ancestor types
                if (sub is OpenApiSchemaReference)
                {
                    foreach (string name in CollectBasePropertyNames(sub))
                    {
                        names.Add(name);
                    }
                }
            }
        }

        return names;
    }

    private static HashSet<string> CollectRequired(IOpenApiSchema schema)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);

        if (schema.Required != null)
        {
            foreach (string r in schema.Required)
            {
                result.Add(r);
            }
        }

        // Collect required from allOf subschemas
        if (schema.AllOf is { Count: > 0 })
        {
            foreach (IOpenApiSchema sub in schema.AllOf)
            {
                if (sub.Required != null)
                {
                    foreach (string r in sub.Required)
                    {
                        result.Add(r);
                    }
                }
            }
        }

        return result;
    }

    private void EmitDocComment(string? description)
    {
        if (!_options.GenerateDocComments || string.IsNullOrWhiteSpace(description))
        {
            return;
        }

        string[] lines = description.Split(["\r\n", "\r", "\n"], StringSplitOptions.None);
        AppendLine("/// <summary>");
        foreach (string line in lines)
        {
            AppendLine($"/// {EscapeXmlDocComment(line)}");
        }
        AppendLine("/// </summary>");
    }

    private void EmitValidationAttributes(IOpenApiSchema schema)
    {
        if (!_options.EmitValidationAttributes)
        {
            return;
        }

        bool isString = TypeResolver.HasTypeFlag(schema, JsonSchemaType.String);
        bool isArray = TypeResolver.HasTypeFlag(schema, JsonSchemaType.Array);
        bool isNumber = TypeResolver.HasTypeFlag(schema, JsonSchemaType.Number) || TypeResolver.HasTypeFlag(schema, JsonSchemaType.Integer);

        if (isString)
        {
            int? minLength = schema.MinLength;
            int? maxLength = schema.MaxLength;

            if (minLength.HasValue || maxLength.HasValue)
            {
                if (minLength.HasValue && maxLength.HasValue)
                {
                    AppendLine($"[StringLength({maxLength.Value}, MinimumLength = {minLength.Value})]");
                }
                else if (maxLength.HasValue)
                {
                    AppendLine($"[StringLength({maxLength.Value})]");
                }
                else
                {
                    AppendLine($"[MinLength({minLength!.Value})]");
                }
            }
        }
        else if (isArray)
        {
            if (schema.MinItems.HasValue)
            {
                AppendLine($"[MinLength({schema.MinItems.Value})]");
            }

            if (schema.MaxItems.HasValue)
            {
                AppendLine($"[MaxLength({schema.MaxItems.Value})]");
            }
        }

        if (isString && !string.IsNullOrEmpty(schema.Pattern))
        {
            AppendLine($"[RegularExpression(\"{EscapeCSharpStringLiteral(schema.Pattern)}\")]");
        }

        if (isNumber && (!string.IsNullOrEmpty(schema.Minimum) || !string.IsNullOrEmpty(schema.Maximum)))
        {
            string min = !string.IsNullOrEmpty(schema.Minimum) ? FormatNumberLiteral(schema.Minimum) : "double.MinValue";
            string max = !string.IsNullOrEmpty(schema.Maximum) ? FormatNumberLiteral(schema.Maximum) : "double.MaxValue";
            AppendLine($"[Range({min}, {max})]");
        }
    }

    private static string FormatNumberLiteral(string value)
    {
        if (decimal.TryParse(value, NumberStyles.Any, CultureInfo.InvariantCulture, out decimal dec))
        {
            if (dec == decimal.Truncate(dec))
            {
                return dec.ToString("0", CultureInfo.InvariantCulture) + "d";
            }

            return dec.ToString(CultureInfo.InvariantCulture) + "d";
        }

        return value;
    }

    private void EmitObsoleteAttribute(IOpenApiSchema schema)
    {
        if (_options.EmitObsoleteAttribute && schema.Deprecated)
        {
            AppendLine("[Obsolete]");
        }
    }

    private static string EscapeXmlDocComment(string text)
    {
        return text
            .Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);
    }

    private static string EscapeCSharpStringLiteral(string text)
    {
        var builder = new StringBuilder(text.Length);

        foreach (char ch in text)
        {
            switch (ch)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\0':
                    builder.Append("\\0");
                    break;
                case '\a':
                    builder.Append("\\a");
                    break;
                case '\b':
                    builder.Append("\\b");
                    break;
                case '\f':
                    builder.Append("\\f");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                case '\v':
                    builder.Append("\\v");
                    break;
                default:
                    if (char.IsControl(ch) || ch is '\u2028' or '\u2029')
                    {
                        builder.Append("\\u");
                        builder.Append(((int) ch).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        builder.Append(ch);
                    }
                    break;
            }
        }

        return builder.ToString();
    }

    /// <summary>
    /// Emits a C# block: the prefix line(s), an opening brace, the body
    /// (at an increased indent level), and a closing brace. Supports
    /// multi-line prefixes (e.g. a declaration followed by a where clause)
    /// by splitting on newlines.
    /// </summary>
    private void AppendBlock(string prefix, Action act)
    {
        foreach (string line in prefix.Split('\n'))
        {
            AppendLine(line.TrimEnd('\r'));
        }

        AppendLine("{");
        _indent++;
        act();
        _indent--;
        AppendLine("}");
    }

    private void AppendLine(string? text = null)
    {
        if (text == null)
        {
            _sb.AppendLine();
        }
        else
        {
            _sb.Append(new string(' ', _indent * 4));
            _sb.AppendLine(text);
        }
    }

    private void Append(string text)
    {
        _sb.Append(new string(' ', _indent * 4));
        _sb.Append(text);
    }

    private void AppendLineRaw(string text)
    {
        _sb.AppendLine(text);
    }

    #endregion
}
